services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/local/bin/start.sh"]
    container_name: improveet-app
    restart: always
    volumes:
      - .:/app
    expose:
      - "9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
      - mysql
    networks:
      - internal

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: improveet
      MYSQL_ROOT_PASSWORD: password
      TZ: 'America/Argentina/Buenos_Aires'
    ports:
      - 3306:3306
    networks:
      - internal
    volumes:
      - ./docker/mysql:/var/lib/mysql

networks:
    internal:
        driver: bridge
