modules:
  with_customers: false
  with_boxes: true

navigation_menu: [
  with_massive_price_update_module: false,
  with_customers_module: false,
  with_users_module: false,
]

products_grid: [
  with_replenish: false,
]

sales_create: [
  with_customer: false,
  with_discount: false,
]

sales_grid: [
  with_customer: false,
  with_zone: false,
  with_siva: false,
]